# Generated by Django 2.1.7 on 2019-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturelocation',
            name='natureUpload',
            field=models.FileField(upload_to='images'),
        ),
    ]
