# Generated by Django 2.1.7 on 2019-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190315_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naturelocation',
            old_name='postCaption',
            new_name='post_caption',
        ),
        migrations.RemoveField(
            model_name='naturelocation',
            name='natureUpload',
        ),
        migrations.AddField(
            model_name='naturelocation',
            name='nature_upload',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
