# Generated by Django 2.1.7 on 2019-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190315_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturelocation',
            name='nature_upload',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
