# Generated by Django 2.1.7 on 2019-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190326_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturelocation',
            name='nature_upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
