# Generated by Django 2.1.7 on 2019-03-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturelocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='NatureLocation',
        ),
    ]
